# Generated by Django 4.0.4 on 2022-06-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('goodsapp', '0002_alter_category_managers_alter_goods_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='goods',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='goods',
            name='site',
            field=models.ManyToManyField(to='sites.site'),
        ),
    ]
