# Generated by Django 4.0.4 on 2022-06-05 11:39

import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0003_alter_goods_managers_alter_goods_site'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager('site')),
            ],
        ),
        migrations.AlterModelManagers(
            name='goods',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager('site')),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='image',
            field=models.ImageField(null=True, upload_to='image_goods/', verbose_name='Изображение'),
        ),
    ]
