# Generated by Django 4.0.4 on 2022-05-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HitCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=512)),
                ('hits', models.IntegerField(default=1)),
                ('user', models.CharField(max_length=128)),
            ],
        ),
    ]
